# Generated by Django 5.0 on 2023-12-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='cms_app/static')),
                ('emailid', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
